name: schecduler to upload gmail attachment to gmail drive

on:
  schedule:
    - cron: '0 22 * * 1'  # Runs on Monday at 22:00 PM BST
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gmail to Drive Script
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        EMAIL_USER: ${{ SECRET_VAULT.EMAIL_USER }}
        EMAIL_PASS: ${{ SECRET_VAULT.EMAIL_PASS }}
        TRUSTED_SENDER: ${{ SECRET_VAULT.TRUSTED_SENDER }}
        DRIVE_FOLDER_ID: ${{ SECRET_VAULT.DRIVE_FOLDER_ID }}
      run: |
        python main.py
